name: Build Refal-05

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        echo "R05CCOMP=gcc -Wall -O3 -g -DR05_POSIX" >> $GITHUB_ENV
        echo "R05PATH=${{ github.workspace }}/lib:${{ github.workspace }}/src:${{ github.workspace }}/src/cfiles" >> $GITHUB_ENV
        chmod +x bin/refal05c
    
    - name: Build new compiler using previous version
      run: |
        cd src
        echo Y | ../bin/refal05c refal05c R05-CompilerUtils R05-Generator R05-Parser LibraryEx R5FW-Parser-Defs R5FW-Parser R5FW-Plainer R5FW-Transformer Platform Library refal05rts
        gcc -Wall -O3 -g -DR05_POSIX -DR05_SHOW_STAT -I../lib -orefal05c refal05c.c R05-CompilerUtils.c R05-Generator.c R05-Parser.c cfiles/LibraryEx.c cfiles/R5FW-Parser-Defs.c cfiles/R5FW-Parser.c cfiles/R5FW-Plainer.c cfiles/R5FW-Transformer.c cfiles/Platform.c ../lib/refal05rts.c ../lib/Library.c
        mv refal05c ../bin/refal05c-new
    
    - name: Run autotests
      run: |
        cd autotests
        ./run.sh
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: refal05c-binary
        path: bin/refal05c-new
        retention-days: 30