name: Build Refal-05

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Bootstrap
      run: ./bootstrap.sh
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: refal05c-linux
        path: bin/refal05c
        retention-days: 30

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Bootstrap
      run: ./bootstrap.bat
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: refal05c-windows
        path: bin/refal05c.exe
        retention-days: 30